### ISSUE TITLE
Provide global.env example

### ISSUE THREAD

**Issue by dgastudio** [ChristophBleyer/go-shopping#21]
Hello, 

global.env file is missing, please, add it

**Comment by ChristophBleyer** [comment]
Hey,

if you run `make` in the root directory the [setup script](https://github.com/ChristophBleyer/go-shopping/blob/main/tools/configure_env.sh) is executed. It will generate that file. If any issues come up feel free to reply.

**Comment by dgastudio** [comment]
oh, i see
thank you
anyway

bash tools/configure_env.sh
tools/configure_env.sh: line 10: pwgen: command not found

means https://github.com/chr4/pwgen ?

**Comment by ChristophBleyer** [comment]
Oh, it is the command line utility. If you are on Mac this is `brew install pwgen` or for example ubuntu `apt-get install -y pwgen`. It is used to auto-generate a password for mysql.

**Comment by dgastudio** [comment]
great, everything seems working fine
thank you!

up:
main.go
	validator := security.NewRedimakesTokenValidator(redisClient)
should be
	validator := security.NewRedisTokenValidator(redisClient)
